spring:
  application:
    name: Holidays
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

